WIP: stop orders
blockworks-foundation/mango-v4-ui pull request #174
Opened 2023-06-16 12:26 UTC by saml33

Adds limit and stop orders to swap and stop orders to spot trade

2023-08-16 14:57 UTC, tlrsssss requested changes
Mostly looks good just some cleanup then can merge

2023-08-16 14:57 UTC, tlrsssss commented on components/swap/SwapTokenChart.tsx
> +
Commented code. Why not show the latest price in the chart?

2023-08-16 14:57 UTC, tlrsssss commented on components/account/AccountTabs.tsx
> +  // }, [isWhiteListed, mangoAccount])
can this be removed?

2023-08-16 14:57 UTC, tlrsssss commented on components/swap/LimitSwapForm.tsx
> +  //   amountInAsDecimal.gt(sellTokenBalance)
Can this be removed?

2023-08-16 14:57 UTC, tlrsssss commented on components/swap/SwapForm.tsx
> +              </div> */}
Can this be removed?

2023-08-16 14:57 UTC, tlrsssss commented on components/swap/SwapTokenChart.tsx
> +    // .concat(latestChartDataItem)
can these be removed?

2023-08-16 14:57 UTC, tlrsssss commented on public/locales/ru/trade.json
> +    "take-profit": "Take-Profit",
Not sure a dash is needed for these

2023-08-16 17:54 UTC, tlrsssss commented
small nit, noticed chart flashes when swapping tokens
https://github.com/blockworks-foundation/mango-v4-ui/assets/1254942/d76a07ac-2d8b-4abb-895f-f7ae14dbf343

2023-08-16 17:55 UTC, tlrsssss commented
https://github.com/blockworks-foundation/mango-v4-ui/assets/1254942/b8f11202-96f9-4aa0-93f2-edd77217c39d

2023-08-16 17:57 UTC, tlrsssss commented
https://github.com/blockworks-foundation/mango-v4-ui/assets/1254942/0f044504-7f35-4e17-a839-261bf6c7b865

small nit, noticed chart flashes when swapping tokens

2023-08-16 22:18 UTC, saml33 commented
> chartbug.mov 
> small nit, noticed chart flashes when swapping tokens
> 
> if you're flipping tokens should the chart flip as well? i think this is what happens on main

Yeah, so it saves the direction if you flip the prices on the trigger order form. It will stay in that direction even when you flip the tokens. Not sure it's necessary and I'm not sure how to get rid of this flicker

2023-08-16 22:20 UTC, tlrsssss commented
> > chartbug.mov
> > small nit, noticed chart flashes when swapping tokens
> > if you're flipping tokens should the chart flip as well? i think this is what happens on main
> 
> Yeah, so it saves the direction if you flip the prices on the trigger order form. It will stay in that direction even when you flip the tokens. Not sure it's necessary and I'm not sure how to get rid of this flicker

I suspect that keeping it in the direction once flipping it, is related to that flicker. If it's not necessary, can try getting rid of it to see if that solves the flicker.

2023-08-16 22:36 UTC, saml33 commented
> > > chartbug.mov
> > > small nit, noticed chart flashes when swapping tokens
> > > if you're flipping tokens should the chart flip as well? i think this is what happens on main
> > 
> > 
> > Yeah, so it saves the direction if you flip the prices on the trigger order form. It will stay in that direction even when you flip the tokens. Not sure it's necessary and I'm not sure how to get rid of this flicker
> 
> I suspect that keeping it in the direction once flipping it, is related to that flicker. If it's not necessary, can try getting rid of it to see if that solves the flicker.

Yeah, it's because of the flipPrices boolean. I think I'll get rid of it. Adding the latestPrice (added back now) also causes a flicker as it needs flipPrices. Maybe it will work if I put it here: fetchChartData

2023-08-17 13:47 UTC, tlrsssss approved these changes
looks good, just need to fix the yarn dedupe

2023-08-17 22:08 UTC, merged