Add a toggle for hiding mangoAccount in leaderboards + search
blockworks-foundation/mango-v4-ui pull request #247
Opened 2023-08-25 09:27 UTC by Lou-Kamades

2023-08-25 11:12 UTC, saml33 commented
Cool. I started this today as well (without the api). Think the setting should go under "Account" so it only shows when a user has an account.

Not sure how you think this should work but I assumed we'd have another endpoint to retrieve all of the private accounts and use the list to block from viewing via url and leaderboard. I've done this with mock data here: https://github.com/blockworks-foundation/mango-v4-ui/tree/private-accounts

2023-08-25 12:29 UTC, Lou-Kamades commented
I agree with you regarding the extra endpoint and how we should block accounts from showing up. I just deployed th endpoint for all private accounts at: https://api.mngo.cloud/data/v4/user-data/private-accounts. Take a look and lmk if this or the other endpoints or request signing doesn't make sense.

I can leave the design/ui work to you for this feature if you'd prefer to do it, I got a little eager with this PR bc I wanted to POC and play with react-query which I'd never used before hahaha

2023-08-30 11:39 UTC, saml33 commented on components/account/HideMangoAccount.tsx
> +            onChange={async () => {
This function should probably be defined as a constant and have a try/catch block

2023-08-30 11:44 UTC, saml33 commented on components/account/AccountHeroStats.tsx
> +                    value={accountPnl}
Can use accountHidden in the component here so we don't repeat the jsx i.e. value={!accountHidden ? accountPnl : 0}

2023-08-30 11:45 UTC, saml33 commented on components/account/AccountHeroStats.tsx
> +                    change={rollingDailyPnlChange}
Can use accountHidden in the component here

2023-09-01 02:08 UTC, tlrsssss requested changes

2023-09-01 02:08 UTC, tlrsssss commented on hooks/useMangoAccountHidden.ts
> +      })
This doesn't look right. I think `isMangoError` only works for v4 client functions. Does this api return a txid for the error?

2023-09-04 21:55 UTC, tlrsssss approved these changes

2023-09-04 22:06 UTC, merged