add notifications sign to mango create account process
blockworks-foundation/mango-v4-ui pull request #254
Opened 2023-08-31 22:29 UTC by abrzezinski94

2023-09-01 02:09 UTC, saml33 commented
I'm not sure we should do this as you can't even create an account on Mango with a Ledger atm

2023-09-01 08:38 UTC, abrzezinski94 commented
> I'm not sure we should do this as you can't even create an account on Mango with a Ledger atm

oh ok so ill remove the isledger thing and just leave sign msg to process

2023-09-01 12:17 UTC, abrzezinski94 commented
ledger check removed

2023-09-03 13:24 UTC, saml33 approved these changes

2023-09-05 14:58 UTC, tlrsssss requested changes
Added a nitpic regarding a type.

This can be added in a followup but I think it would be useful to have a little info icon with a tooltip on the UserSetupModal explaining what the notifications are for.

2023-09-05 14:58 UTC, tlrsssss commented on components/account/CreateAccountForm.tsx
> +  const [singToNotifications, setSignToNotifications] = useState(true)
nitpick: "sign" is misspelled here

2023-09-05 14:58 UTC, tlrsssss commented on components/modals/UserSetupModal.tsx
> +  const [singToNotifications, setSignToNotifications] = useState(true)
same typo here

2023-09-05 18:50 UTC, merged